import { motion, useMotionValue, useTransform } from "framer-motion";
import { ArrowRight, Sparkles, Play, Terminal } from "lucide-react";
import { useState, useEffect } from "react";

const typewriterLines = [
  { text: "// Generated by IntelliPlan AI", color: "text-muted-foreground" },
  { text: "describe('User Authentication Flow', () => {", color: "text-foreground" },
  { text: "  it('should login with valid credentials', async () => {", color: "text-foreground" },
  { text: "    await page.navigate('/login');", color: "text-foreground" },
  { text: "    await page.fill('#email', testData.email);", color: "text-foreground" },
  { text: "    await page.fill('#password', testData.password);", color: "text-foreground" },
  { text: "    await page.click('[data-testid=\"login-btn\"]');", color: "text-foreground" },
  { text: "    expect(page.url()).toBe('/dashboard');", color: "text-foreground" },
  { text: "  });", color: "text-foreground" },
  { text: "});", color: "text-foreground" },
];

function TypewriterCode() {
  const [visibleLines, setVisibleLines] = useState(0);
  const [charIndex, setCharIndex] = useState(0);

  useEffect(() => {
    if (visibleLines >= typewriterLines.length) return;

    const currentLine = typewriterLines[visibleLines];
    if (charIndex < currentLine.text.length) {
      const timer = setTimeout(() => setCharIndex((c) => c + 1), 25);
      return () => clearTimeout(timer);
    } else {
      const timer = setTimeout(() => {
        setVisibleLines((l) => l + 1);
        setCharIndex(0);
      }, 100);
      return () => clearTimeout(timer);
    }
  }, [visibleLines, charIndex]);

  return (
    <div className="font-mono text-xs sm:text-sm leading-relaxed">
      {typewriterLines.map((line, i) => {
        if (i > visibleLines) return null;
        const displayText = i === visibleLines ? line.text.slice(0, charIndex) : line.text;

        // Syntax highlighting
        const highlighted = displayText
          .replace(/(describe|it|expect|await|async|const)/g, '<span class="text-primary">$1</span>')
          .replace(/('.*?')/g, '<span class="text-emerald">$1</span>')
          .replace(/(\/\/.*)/g, '<span class="text-accent">$1</span>')
          .replace(/(\.[a-zA-Z]+)\(/g, '<span class="text-amber">$1</span>(');

        return (
          <div key={i} className="min-h-[1.5em]">
            <span dangerouslySetInnerHTML={{ __html: highlighted }} />
            {i === visibleLines && visibleLines < typewriterLines.length && (
              <span className="inline-block w-2 h-4 ml-0.5 bg-primary animate-pulse" />
            )}
          </div>
        );
      })}
    </div>
  );
}

const floatingBadges = [
  { text: "Playwright", delay: 0, x: -60, y: -30 },
  { text: "Selenium", delay: 0.3, x: 60, y: -50 },
  { text: "Cypress", delay: 0.6, x: -80, y: 30 },
  { text: "Jest", delay: 0.9, x: 70, y: 40 },
];

export function Hero() {
  const mouseX = useMotionValue(0);
  const mouseY = useMotionValue(0);
  const x = useTransform(mouseX, [0, 1], [-10, 10]);
  const y = useTransform(mouseY, [0, 1], [-10, 10]);

  const handleMouseMove = (e: React.MouseEvent) => {
    const rect = e.currentTarget.getBoundingClientRect();
    mouseX.set((e.clientX - rect.left) / rect.width);
    mouseY.set((e.clientY - rect.top) / rect.height);
  };

  return (
    <section
      onMouseMove={handleMouseMove}
      className="relative flex items-center justify-center overflow-hidden pt-24 pb-16"
    >
      {/* Background layers */}
      <div className="absolute inset-0 hero-glow" />
      <div className="absolute inset-0 hero-glow-violet" />

      <div className="relative z-10 mx-auto max-w-6xl px-6 text-center">
        {/* Badge */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="mb-8 inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/5 px-5 py-2 text-sm text-primary glass"
        >
          <Sparkles className="h-3.5 w-3.5" />
          <span>AI-Powered Test Intelligence Platform</span>
          <ArrowRight className="h-3 w-3" />
        </motion.div>

        {/* Brand Name */}
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.8, delay: 0.1 }}
          style={{ x, y }}
        >
          <h1 className="text-6xl sm:text-7xl lg:text-8xl font-black tracking-tighter">
            <span className="text-gradient">IntelliPlan AI</span>
          </h1>
        </motion.div>

        {/* Tagline */}
        <motion.p
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="mt-4 text-3xl sm:text-4xl lg:text-5xl font-bold tracking-tight"
        >
          From Requirements to{" "}
          <span className="relative inline-block">
            <span className="text-gradient-cyan">Automation</span>
            <motion.span
              className="absolute -bottom-1 left-0 h-0.5 bg-primary/60 rounded-full"
              initial={{ width: 0 }}
              animate={{ width: "100%" }}
              transition={{ duration: 1, delay: 1 }}
            />
          </span>
          <br />
          <span className="text-muted-foreground font-semibold">— Instantly.</span>
        </motion.p>

        <motion.p
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.3 }}
          className="mx-auto mt-6 max-w-2xl text-base sm:text-lg text-muted-foreground leading-relaxed"
        >
          Generate comprehensive test plans, detailed test cases, and production-ready
          automation code — all powered by AI. Ship quality software faster than ever.
        </motion.p>

        {/* CTA Buttons */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.4 }}
          className="mt-10 flex flex-col items-center gap-4 sm:flex-row sm:justify-center"
        >
          <button className="group relative overflow-hidden flex items-center gap-2 rounded-xl bg-primary px-7 py-3.5 text-sm font-semibold text-primary-foreground transition-all hover:shadow-2xl hover:shadow-primary/30">
            <span className="relative z-10 flex items-center gap-2">
              Start Building Tests
              <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" />
            </span>
            <div className="absolute inset-0 shimmer-bg opacity-0 group-hover:opacity-100 transition-opacity" />
          </button>
          <button className="group flex items-center gap-2 rounded-xl border border-border px-7 py-3.5 text-sm font-medium text-foreground transition-all hover:border-primary/30 hover:bg-secondary">
            <Play className="h-4 w-4 text-primary" />
            Watch Demo
          </button>
        </motion.div>

        {/* Code Preview with Typewriter */}
        <motion.div
          initial={{ opacity: 0, y: 60 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.6 }}
          className="relative mx-auto mt-14 max-w-3xl"
        >
          {/* Floating framework badges */}
          {floatingBadges.map((badge) => (
            <motion.div
              key={badge.text}
              initial={{ opacity: 0, scale: 0.8 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: badge.delay + 1.5, duration: 0.4 }}
              className="absolute z-20 hidden lg:block"
              style={{ left: badge.x < 0 ? badge.x : "auto", right: badge.x > 0 ? -badge.x : "auto", top: badge.y < 0 ? badge.y : "auto", bottom: badge.y > 0 ? -badge.y : "auto" }}
            >
              <div className="animate-float-slow rounded-lg border border-border bg-card/90 glass px-3 py-1.5 text-xs font-medium text-foreground shadow-lg" style={{ animationDelay: `${badge.delay * 2}s` }}>
                {badge.text}
              </div>
            </motion.div>
          ))}

          <div className="glow-border rounded-2xl bg-card/80 glass overflow-hidden">
            {/* Terminal header */}
            <div className="flex items-center gap-3 border-b border-border/50 px-5 py-3">
              <div className="flex gap-1.5">
                <div className="h-3 w-3 rounded-full bg-destructive/60" />
                <div className="h-3 w-3 rounded-full bg-amber/60" />
                <div className="h-3 w-3 rounded-full bg-emerald/60" />
              </div>
              <div className="flex items-center gap-2 ml-2">
                <Terminal className="h-3 w-3 text-muted-foreground" />
                <span className="font-mono text-xs text-muted-foreground">intelliplan-output.spec.ts</span>
              </div>
              <div className="ml-auto flex items-center gap-1.5">
                <div className="h-1.5 w-1.5 rounded-full bg-emerald animate-pulse" />
                <span className="text-[10px] text-emerald font-mono">GENERATING</span>
              </div>
            </div>
            {/* Code content */}
            <div className="p-5 text-left">
              <TypewriterCode />
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
